export const tokens = {
  color: {
    light: {
      canvas: "#f7f2e8",
      surface: "#fffdf8",
      surfaceSubtle: "#eee9df",
      text: "#202421",
      textMuted: "#555d58",
      border: "#c8ccc4",
      controlBorder: "#727a74",
      action: "#0c5c55",
      onAction: "#ffffff",
      success: "#27623f",
      onSuccess: "#ffffff",
      warning: "#785313",
      onWarning: "#ffffff",
      danger: "#a2342e",
      onDanger: "#ffffff",
      focus: "#087e73",
    },
    dark: {
      canvas: "#151815",
      surface: "#1d211e",
      surfaceSubtle: "#292e2a",
      text: "#f2efe7",
      textMuted: "#b7bdb6",
      border: "#555d57",
      controlBorder: "#8a928b",
      action: "#86cfc3",
      onAction: "#102420",
      success: "#8bd3a8",
      onSuccess: "#10271a",
      warning: "#e7c178",
      onWarning: "#2c210d",
      danger: "#ffb4ac",
      onDanger: "#3b0a08",
      focus: "#9ee9dc",
    },
  },
  font: {
    family: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI Variable", "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    monoNumeric: "tabular-nums",
    size: { small: "0.875rem", body: "1rem", title: "1.5rem" },
    lineHeight: { small: "1.35", body: "1.5", title: "1.2" },
  },
  space: { 1: "0.25rem", 2: "0.5rem", 3: "0.75rem", 4: "1rem", 6: "1.5rem", 8: "2rem" },
  radius: { control: "0.5rem", card: "0.625rem" },
  size: { touch: "2.75rem", icon: "1.25rem" },
  border: { width: "1px" },
  focus: { width: "3px", offset: "2px" },
  elevation: { raised: "0 1px 2px rgb(20 24 21 / 0.08)" },
  motion: { quick: "120ms", standard: "180ms", skeleton: "1400ms", easing: "cubic-bezier(0.2, 0, 0, 1)" },
  breakpoint: { compact: "30rem", wide: "64rem" },
  layout: { contentMax: "75rem", readingMax: "42rem" },
} as const;

export type ThemeName = keyof typeof tokens.color;
export type ThemeColors = (typeof tokens.color)[ThemeName];
